POC-01
LimeChain/SupplyChainPOCs pull request #1
Opened 2020-01-09 20:56 UTC by failfmi

Chaincode & Unit tests

2020-01-10 13:07 UTC, Holymir commented on chaincode.go
> +	if order.IsCompleted == true {
no need to == true  maybe?

2020-01-10 14:31 UTC, Perseverance requested changes

2020-01-10 14:31 UTC, Perseverance commented on chaincode.go
> +	organizations, _ := json.Marshal(args)
What is the second param about. If it is an error I think it is good idea to catch it and throw. Otherwise we might not know during testing that we've initialised the chaincode with something broken.

2020-01-10 14:31 UTC, Perseverance commented on chaincode.go
> +	err := json.Unmarshal([]byte(args[0]), &order)
Lets check if the order.AssetId is an existing AssetId

2020-01-10 14:31 UTC, Perseverance commented on chaincode.go
> +			AssetId: record.AssetId,
Looking at it, I am wondering whether we should also have a param field "creationOrderId" in order for us to be able to find all records created via fulfilment of a certain order

2020-01-16 10:20 UTC, Perseverance requested changes

2020-01-16 10:20 UTC, Perseverance commented on cc/SupplyChainChaincode.go
> +func (scc *SupplyChainChaincode) Query(stub shim.ChaincodeStubInterface, args [] string) peer.Response {
Do we need Query in the abstract chaincode, shouldnt this be defined in the developer-implemented chaincode (POC1Chaincode)?

2020-01-20 09:24 UTC, Perseverance requested changes

2020-01-20 09:24 UTC, Perseverance commented on examples/poc01_1/poc01_1.go
> +	case constants.Create:
I think this should be Manufacture. The "endpoint" should be manufacture, even the chaincode method might be manufacture, but it needs to be calling the abstract `create` method of the base chaincode

2020-01-20 09:24 UTC, Perseverance commented on examples/poc01_1/poc01_1.go
> +	case constants.Compose:
I think this should be assemble

2020-01-20 13:03 UTC, Perseverance approved these changes

2020-01-24 09:28 UTC, Perseverance approved these changes

2020-01-24 09:28 UTC, merged